FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy application files and requirements in one step
COPY ./app.py ./requirements.txt ./

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set the default command
CMD ["python", "app.py"]
