version: "3.8"

services:
  node:
    build: ./app  # ✅ Uses a Dockerfile instead of just pulling an image
    container_name: node-app
    working_dir: /app
    volumes:
      - ./app:/app
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"
    command: ["sh", "-c", "sleep 5 && npm start"]  # ✅ Delay startup
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres-data:
  node-modules:
