
services:
  node:
    build: ./app  # ✅ Build using a Dockerfile in the ./app directory
    container_name: node-app
    working_dir: /app
    volumes:
      - ./app:/app  # ✅ Sync application source code
    ports:
      - "3000:3000"
    command: ["sh", "-c", "sleep 5 && npm start"]  # ✅ Delay startup to ensure DB readiness
    env_file:
      - .env
    depends_on:
      - db
    restart: always  # ✅ Restart if the container crashes

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data  # ✅ Persistent data storage
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:  # ✅ Persistent PostgreSQL data
